# Generated by Django 3.1.5 on 2021-10-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='content_rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
