# Generated by Django 3.1.5 on 2021-10-29 20:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_auto_20211029_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='imdb',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
