# Generated by Django 3.1.5 on 2021-11-04 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_auto_20211029_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='photo',
            new_name='photo_url',
        ),
    ]
