# Generated by Django 3.1.5 on 2021-11-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0006_auto_20211104_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='film',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
