# Generated by Django 3.1.5 on 2021-11-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0007_auto_20211104_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners'),
        ),
        migrations.AlterField(
            model_name='film',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='posters'),
        ),
    ]
